In [1]:
import pandas as pd
import re

In [75]:
df = pd.read_csv("../data/raw/indian_spam.csv")

df.columns = ["labels", "messages"]

df["numerical_labels"] = df["labels"].apply(
    lambda x: 0 if x == "ham" else 1
)

In [76]:
def clean_text(text):
    text = str(text)
    text = text.lower()
    text = re.sub(r"http\S+|www\S+", " <URL> ", text)
    text = re.sub(r"\d+", "<NUMBER>", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text

In [77]:
test_message = "CONGRATULATIONS!!! You won ₹50,000. Visit www.example.com NOW!"

print("Original:", test_message)

print("Cleaned:", clean_text(test_message))

Original: CONGRATULATIONS!!! You won ₹50,000. Visit www.example.com NOW!
Cleaned: congratulations!!! you won ₹<NUMBER>,<NUMBER>. visit <URL> now!

In [78]:
df["cleaned_message"] = df["messages"].apply(clean_text)

In [79]:
print(df["cleaned_message"].head())

0       zyada itrao mat . english meko bi aati hai :-p
1    is ajnbi dunia me akle <NUMBER> khwab hu swalo...
2    husband n wife were opening joint bank ac husb...
3    husband suhag raat pe- tum ne kabhi blue film ...
4    indagi me <NUMBER> cheez kabhi bhi aa sakti h ...
Name: cleaned_message, dtype: str

In [80]:
df["cleaned_message"].isnull().sum()

np.int64(0)

In [81]:
df["cleaned_message"].duplicated().sum()

np.int64(61)

In [82]:
df[df["cleaned_message"].duplicated(keep=False)].sort_values("cleaned_message").head(6)

,labels,messages,numerical_labels,cleaned_message
827,ham,I dont know bout it. But we wont be in same co...,0,i dont know bout it. but we wont be in same co...
826,ham,I dont know bout it. But we wont be in same co...,0,i dont know bout it. but we wont be in same co...
824,ham,I dont know wy he offer tat. I think want to s...,0,i dont know wy he offer tat. i think want to s...
825,ham,I dont know wy he offer tat. I think want to s...,0,i dont know wy he offer tat. i think want to s...
820,ham,I dont remember anythin . U r very late to giv...,0,i dont remember anythin . u r very late to giv...
819,ham,I dont remember anythin . U r very late to giv...,0,i dont remember anythin . u r very late to giv...

In [83]:
df = df.drop_duplicates()
df.shape

(1999, 4)

In [84]:
df.columns

Index(['labels', 'messages', 'numerical_labels', 'cleaned_message'], dtype='str')

In [89]:
df = df.drop(columns=["labels"])

In [90]:
df.columns

Index(['messages', 'numerical_labels', 'cleaned_message'], dtype='str')

In [91]:
df.head()

,messages,numerical_labels,cleaned_message
0,zyada itrao mat . english meko bi aati hai :-P,0,zyada itrao mat . english meko bi aati hai :-p
1,is ajnbi dunia me akle 1 khwab hu swalon se k...,0,is ajnbi dunia me akle <NUMBER> khwab hu swalo...
2,Husband n wife were opening joint bank ac Husb...,0,husband n wife were opening joint bank ac husb...
3,Husband Suhag raat pe- Tum ne kabhi Blue Film ...,0,husband suhag raat pe- tum ne kabhi blue film ...
4,indagi me 5 cheez kabhi bhi aa sakti h 'Hum' '...,0,indagi me <NUMBER> cheez kabhi bhi aa sakti h ...

In [94]:
df.index.name = "Id"

In [95]:
df.head()

,messages,numerical_labels,cleaned_message
Id,,,
0,zyada itrao mat . english meko bi aati hai :-P,0,zyada itrao mat . english meko bi aati hai :-p
1,is ajnbi dunia me akle 1 khwab hu swalon se k...,0,is ajnbi dunia me akle <NUMBER> khwab hu swalo...
2,Husband n wife were opening joint bank ac Husb...,0,husband n wife were opening joint bank ac husb...
3,Husband Suhag raat pe- Tum ne kabhi Blue Film ...,0,husband suhag raat pe- tum ne kabhi blue film ...
4,indagi me 5 cheez kabhi bhi aa sakti h 'Hum' '...,0,indagi me <NUMBER> cheez kabhi bhi aa sakti h ...

In [ ]:
df.to_save("../data/processed/indian_spam_processed.csv", index = false)